Removed extraneous semicolon

diff --git a/git-flow-tower-feature b/git-flow-tower-feature
--- a/git-flow-tower-feature
+++ b/git-flow-tower-feature
@@ -344,8 +344,8 @@ no-ff!                 Never fast-forward during the merge
 	if flag fetch; then
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
 	fi
-	
-	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+
+	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
 
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
diff --git a/git-flow-tower-hotfix b/git-flow-tower-hotfix
--- a/git-flow-tower-hotfix
+++ b/git-flow-tower-hotfix
@@ -391,7 +391,7 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 		[ "$BASE_BRANCH" = "$MASTER_BRANCH" ] && git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
-	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
 
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
diff --git a/git-flow-tower-release b/git-flow-tower-release
--- a/git-flow-tower-release
+++ b/git-flow-tower-release
@@ -246,7 +246,7 @@ _finish_base() {
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
 	fi
 
-	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
 
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
