Streamlining
Publish only if nonexistant on remote
Push everytime after fetch

diff --git a/git-flow-tower-feature b/git-flow-tower-feature
--- a/git-flow-tower-feature
+++ b/git-flow-tower-feature
@@ -335,12 +335,17 @@ no-ff!                 Never fast-forward during the merge
 	# merged into the local branch
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		git_fetch_branch "$ORIGIN" "$BRANCH"
+	else
+		cmd_publish "$NAME"
 	fi
+
 
 	# Update local branches with remote branches
 	if flag fetch; then
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
 	fi
+	
+	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
 
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
@@ -349,8 +354,6 @@ no-ff!                 Never fast-forward during the merge
 	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
 		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
 	fi
-	
-	cmd_publish "$NAME"
 
 	run_pre_hook "$NAME" "$ORIGIN" "$BRANCH"
 
diff --git a/git-flow-tower-hotfix b/git-flow-tower-hotfix
--- a/git-flow-tower-hotfix
+++ b/git-flow-tower-hotfix
@@ -381,6 +381,8 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 	# merged into the local branch
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		git_fetch_branch "$ORIGIN" "$BRANCH"
+	else
+		cmd_publish "$NAME"
 	fi
 
 	# Update local branches with remote branches
@@ -389,11 +391,11 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 		[ "$BASE_BRANCH" = "$MASTER_BRANCH" ] && git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
+	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
-	# else
-	# 	cmd_publish "$NAME"
 	fi
 
 	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
@@ -404,8 +406,6 @@ b,[no]nobackmerge     Don't back-merge master, or tag if applicable, in develop
 			require_branches_equal "$DEVELOP_BRANCH" "$ORIGIN/$DEVELOP_BRANCH"
 		fi
 	fi
-	
-	cmd_publish "$NAME"
 
 	# If the branch is already merged there is no need to check the hotfix branch
 	# This can happen when the merge in develop fails and we rerun the finish.
diff --git a/git-flow-tower-release b/git-flow-tower-release
--- a/git-flow-tower-release
+++ b/git-flow-tower-release
@@ -51,6 +51,8 @@ _finish_from_develop() {
 		git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
+	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
@@ -147,13 +149,7 @@ _finish_from_develop() {
 
 	git_do checkout "$BASE_BRANCH" || die "Could not check out branch '$BASE_BRANCH'."
 	run_post_hook "$VERSION_PREFIX$VERSION" "$ORIGIN" "$BRANCH"
-
-	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
-		echo "";
-	else
-		cmd_publish "$NAME"
-	fi
-
+	
 	# # Delete branch
 	# if noflag keep; then
 
@@ -250,6 +246,8 @@ _finish_base() {
 		git_fetch_branch "$ORIGIN" "$BASE_BRANCH"
 	fi
 
+	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 		require_branches_equal "$BRANCH" "$ORIGIN/$BRANCH"
@@ -259,8 +257,6 @@ _finish_base() {
 	if git_remote_branch_exists "$ORIGIN/$BASE_BRANCH"; then
 		require_branches_equal "$BASE_BRANCH" "$ORIGIN/$BASE_BRANCH"
 	fi
-
-	cmd_publish "$NAME"
 
 	if noflag notag; then
 		# We ask for a tag, be sure it does not exists or
@@ -676,6 +672,8 @@ S,[no]squash        Squash release during merge
 	# merged into the local branch
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
 			git_fetch_branch "$ORIGIN" "$BRANCH"
+	else
+		cmd_publish "$NAME"
 	fi
 
 	if [ "$BASE_BRANCH" = "$DEVELOP_BRANCH" ]; then
