Removed typo

diff --git a/git-flow-tower-release b/git-flow-tower-release
--- a/git-flow-tower-release
+++ b/git-flow-tower-release
@@ -51,7 +51,7 @@ _finish_from_develop() {
 		git_fetch_branch "$ORIGIN" "$DEVELOP_BRANCH"
 	fi
 
-	git_do push "$ORIGIN" :"$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
+	git_do push "$ORIGIN" "$BRANCH" || die "Could not push the $BRANCH to $ORIGIN."
 
 	# Check if the local branches have all the commits from the remote branches
 	if git_remote_branch_exists "$ORIGIN/$BRANCH"; then
